[features]
seeds = false
skip-lint = false

[programs.devnet]
nft_lend_borrow = "DJ2yQBUMwFkB3cWsVbUZZ4DxmkR4pFf6KxrZMEDD1uwH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
